name = "cf-image-proxy"
type = "javascript"
webpack_config = "webpack.config.js"
account_id = "daa8cdc9e1c3b6edab418d8ada42cf8a"
workers_dev = true

[env.production]
zone_id = "432f1dbaf824bf1e573d886fa4e872a5"
route = "winter-field-cakefree.huguadao.workers.dev"
